### PR TITLE
Added MountFujiWindowsInstaller project that creates an Inno Setup-based installer for the Windows version of MountFuji.

### PR DESCRIPTION
**Pull request by hunsra**
Addresses issue #9

### CODE REVIEW

**Comment by davidblackuk** [comment]
Ill start with a huge apology for taking so long to get to this. Life has been a little lively of late.

This is awesome stuff. I built the installer, took a while since i downloded the SDK not the runtime and spent ages looking at an error that told me exactly what was wrong and just not seeing it.

Tested it on windows 10 and it worked a charm. Its really cool. I don't think the msix will be needed in the future as this looks like a solid approach.

I'll mege it down.

One question. in the gitignore for the runtime files do you think it would be advisable to wild card it, so we don't need to change the gitignore each time we change te runtime version. I already went 8.0.4 -> 8.0.5 -> 8.0.6 while testing this.

I do like how easy youve made changing the framwork version via constants.

**Comment by hunsra** [comment]
Hi David!  No need to apologize, this is all just fun stuff to work on and there's no hurry for any of it.  I hope the liveliness has died down a bit.  I saw that you released a new video on YT, so I knew you were back at it.

Yeah, I agree the .gitignore file should be wildcarded to avoid having to tweak it with each new runtime version.  Let me know if you'll do that or you prefer I do.

**Comment by hunsra** [comment]
One other idea I had while making the installer was to include a default configuration file that points to the hatari.mfhat file that gets put into place by the installer.  That way the end user doesn't have to adjust that unless they want to.

If you look closely, you might notice that I accidentally left a "preferences.json" file in the Assets folder of the installer project.  This was the beginning of me investigating this.  It's currently unused, but could be continued with to support being edited by the installer have the proper path and then copied to the right place on the target computer.

 What do you think?

**Comment by davidblackuk** [comment]
Hi Randy

Populating the default path to the mfhat for a first install makes perfect sense. I guess if it’s a subsequent install we should skip it. Is that possible.

Another point is that if the user installed the old msix app, the upgrade instructions need to say to back up your old config first via the link on the about dialog. Then install and copy the files to the new location. In this case we may need to modify the existing config file for the new .mfhatnfile.

Thoughts?

D.

**Comment by hunsra** [comment]
> Hi Randy Populating the default path to the mfhat for a first install makes perfect sense. I guess if it’s a subsequent install we should skip it. Is that possible. Another point is that if the user installed the old msix app, the upgrade instructions need to say to back up your old config first via the link on the about dialog. Then install and copy the files to the new location. In this case we may need to modify the existing config file for the new .mfhatnfile. Thoughts? D.

Yeah, I can add a check for the pre-existence of the preferences.json file and not overwrite it if it's already there, just modify it if needed.  I suppose some care should also be taken with the .mfhat file as well.  Maybe make sure it's properly associated if it exists or add and associated if it doesn't.

Good point about an existing msix app.  I wonder if its possible to have the installer handle this automatically?  It could look for the msix appand copy its preferences.json file on the user's behalf.  It could even modify the file to point to the possibly new .mfhat file.  I'll need to do some investigation on where the msix app stores preferences.json to be sure this can be done.

**Comment by davidblackuk** [comment]
Hi Randy

Don’t panic if you see a new draft release in the Repo. I’m not pulling the trigger. I’ve just added a check for updates feature and I need this to test.

D

**Comment by hunsra** [comment]
download

No panicking here.

Just noticed a few small issues:

1. When built unpackaged, the data folder becomes:  `{AppData}\User Name\com.overtakenbyevents.mountfuji\Data\fuji` (that's a literal "User Name" in the path).  This doesn't happen when MSI-packaged.  I can remove the "User Name" part by adjusting the application metadata.  I think this is in Package.appxmanifest in the Windows platform files.  Perhaps change it to "David Black" or just leave blank.  What do you think?
2. I inadvertently pushed the actual executable output of the installer project to GitHub in the Output folder.  I don't think this should be included.  I can try to remove it and exclude it with .gitignore.  What do you think?

**Comment by davidblackuk** [comment]
> On 4 Jun 2024, at 14:49, Randy S. Hunsaker ***@***.***> wrote:
> 
> 
> download.jpg (view on web) <https://github.com/davidblackuk/MountFuji/assets/746214/438c5bb5-9a24-4783-be57-4ce9a67e3895>
> No panicking here.
> 
> Just noticed a few small issues:
> 
> When built unpackaged, the data folder becomes: {AppData}\User Name\com.overtakenbyevents.mountfuji\Data\fuji (that's a literal "User Name" in the path). This doesn't happen when MSI-packaged. I can remove the "User Name" part by adjusting the application metadata. I think this is in Package.appxmanifest in the Windows platform files. Perhaps change it to "David Black" or just leave blank. What do you think?
Is this an install for this or install for all users thing? I’d say do what you think best as long as it’s an invariant. IIRC the mix version had a product id in it that changed for each version I released (or at least when swapping debug to release), not good.

If we can't upgrade from 1.0.X automatically, we can do it through instructions in the readme.

> I inadvertently pushed the actual executable output of the installer project to GitHub in the Output folder. I don't think this should be included. I can try
> to remove it and exclude it with .gitignore. What do you think?
As you say, I think we should delete it from GitHub through the ui and then add it to the git ignore. Could you also change the rule for the runtime files when you’re in there>

**Comment by hunsra** [comment]
> Is this an install for this or install for all users thing? I’d say do what you think best as long as it’s an invariant. IIRC the mix version had a product id in it that changed for each version I released (or at least when swapping debug to release), not good. If we can't upgrade from 1.0.X automatically, we can do it through instructions in the readme.

This isn't an install for current user/all users thing.  I think it's because of the `Persistence` class' use of `FileSystem.AppDataDirectory` for the root of the folder.  It's user-specific and includes some static metadata from the application.  So, for my user, the AppDataDirectory value is:

`C:\Users\randy\AppData\Roaming\User Name\com.overtakenbyevents.mountfuji\Data`

I don't think .NET MAUI provides any other special folder access, so I don't think we can modify this to be the same folder for all users, but the remaining portion after the `C:\Users\randy\AppData\Roaming` part is already invariant.  I'll make the "User Name" part be "David Black" instead.  I also think I can handle 1.0.X version upgrades without an issue by searching for any folder matching "com.overtakenbyevents.mountfuji_*" in the user's local packages folder.  The last MSIX-packaged version puts its data in the `C:\Users\randy\AppData\Local\Packages\com.overtakenbyevents.mountfuji_9s7pqp8tfze56\LocalState\fuji` folder for my user, so this should be an effective way of retaining settings from previous version.  I'll also copy any of the other configuration files found there to the new folder.

> As you say, I think we should delete it from GitHub through the ui and then add it to the git ignore. Could you also change the rule for the runtime files when you’re in there>

Yep. I'll take care of all of that.

**Comment by hunsra** [comment]
Hi David, I made a new PR (#32) with the changes we discussed.  Let me know what you think.

**Pull request merged**
